### ISSUE TITLE
Dependency issue with version 2.5

### ISSUE THREAD

**Issue by codeskraps** [astrapi69/jgeohash#22]
Upgrading from version 2.4.0 to 2.5, it is giving me a compile time issue.

>[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':game:transformResourcesWithMergeJavaResForNightlyDebug'.
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > More than one file was found with OS independent path 'log4j.properties'
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.  Run with --scan to get full 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
[ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
[ERROR] [org.gradle.internal.buildevents.BuildResultLogger] 
[ERROR] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED in 1m 33s

I also tried adding this without any luck as this creates another similar issue without ending:

`packagingOptions{
    exclude 'log4j.properties'
}`

checking my project dependencies I notices that the dependencies from version 2.4.0 and 2.5 are quite substantial:

**2.4.0**

> +--- de.alpharogroup:jgeohash-core:2.4.0
|    +--- com.maxmind.geoip:geoip-api:1.2.14
|    +--- org.projectlombok:lombok:1.16.16
|    +--- org.slf4j:slf4j-log4j12:1.6.4
|    |    +--- org.slf4j:slf4j-api:1.6.4
|    |    \--- log4j:log4j:1.2.16
|    +--- org.slf4j:slf4j-api:1.6.4
|    \--- log4j:log4j:1.2.16

**2.5**

> +--- de.alpharogroup:jgeohash-core:2.5
|    +--- de.alpharogroup:jobject-merge:1.11
|    |    +--- de.alpharogroup:jobject-copy:1.11
|    |    |    +--- commons-beanutils:commons-beanutils:1.9.3
|    |    |    |    +--- commons-logging:commons-logging:1.2
|    |    |    |    \--- commons-collections:commons-collections:3.2.2
|    |    |    +--- de.alpharogroup:jobject-core:1.11
|    |    |    |    +--- org.projectlombok:lombok:1.16.20
|    |    |    |    +--- org.slf4j:slf4j-api:1.7.25
|    |    |    |    +--- org.slf4j:slf4j-log4j12:1.7.25
|    |    |    |    |    \--- org.slf4j:slf4j-api:1.7.25
|    |    |    |    +--- org.apache.logging.log4j:log4j-api:2.11.0
|    |    |    |    \--- org.apache.logging.log4j:log4j-core:2.11.0
|    |    |    |         \--- org.apache.logging.log4j:log4j-api:2.11.0
|    |    |    +--- org.projectlombok:lombok:1.16.20
|    |    |    +--- org.slf4j:slf4j-api:1.7.25
|    |    |    +--- org.slf4j:slf4j-log4j12:1.7.25 (*)
|    |    |    +--- org.apache.logging.log4j:log4j-api:2.11.0
|    |    |    \--- org.apache.logging.log4j:log4j-core:2.11.0 (*)
|    |    +--- de.alpharogroup:jobject-core:1.11 (*)
|    |    +--- commons-beanutils:commons-beanutils:1.9.3 (*)
|    |    +--- org.projectlombok:lombok:1.16.20
|    |    +--- org.slf4j:slf4j-api:1.7.25
|    |    +--- org.slf4j:slf4j-log4j12:1.7.25 (*)
|    |    +--- org.apache.logging.log4j:log4j-api:2.11.0
|    |    \--- org.apache.logging.log4j:log4j-core:2.11.0 (*)
|    +--- com.maxmind.geoip:geoip-api:1.2.14
|    +--- de.alpharogroup:jcommons-lang:4.34
|    |    +--- org.apache.commons:commons-collections4:4.1
|    |    +--- commons-io:commons-io:2.6
|    |    +--- commons-codec:commons-codec:1.11
|    |    +--- org.apache.commons:commons-lang3:3.7
|    |    +--- joda-time:joda-time:2.10
|    |    +--- de.alpharogroup:silly-collections:4.29
|    |    |    +--- org.apache.commons:commons-collections4:4.1
|    |    |    +--- de.alpharogroup:jobject-compare:1.11
|    |    |    |    +--- commons-beanutils:commons-beanutils:1.9.3 (*)
|    |    |    |    +--- org.projectlombok:lombok:1.16.20
|    |    |    |    +--- org.slf4j:slf4j-api:1.7.25
|    |    |    |    +--- org.slf4j:slf4j-log4j12:1.7.25 (*)
|    |    |    |    +--- org.apache.logging.log4j:log4j-api:2.11.0
|    |    |    |    \--- org.apache.logging.log4j:log4j-core:2.11.0 (*)
|    |    |    +--- de.alpharogroup:jobject-core:1.11 (*)
|    |    |    +--- org.projectlombok:lombok:1.16.20
|    |    |    +--- org.slf4j:slf4j-api:1.7.25
|    |    |    +--- org.slf4j:slf4j-log4j12:1.7.25 (*)
|    |    |    +--- org.apache.logging.log4j:log4j-api:2.11.0
|    |    |    \--- org.apache.logging.log4j:log4j-core:2.11.0 (*)
|    |    +--- de.alpharogroup:jobject-core:1.11 (*)
|    |    +--- de.alpharogroup:jobject-diff:1.11
|    |    |    +--- commons-beanutils:commons-beanutils:1.9.3 (*)
|    |    |    +--- de.alpharogroup:jobject-compare:1.11 (*)
|    |    |    +--- de.alpharogroup:jobject-core:1.11 (*)
|    |    |    +--- org.projectlombok:lombok:1.16.20
|    |    |    +--- org.slf4j:slf4j-api:1.7.25
|    |    |    +--- org.slf4j:slf4j-log4j12:1.7.25 (*)
|    |    |    +--- org.apache.logging.log4j:log4j-api:2.11.0
|    |    |    \--- org.apache.logging.log4j:log4j-core:2.11.0 (*)
|    |    +--- org.projectlombok:lombok:1.16.20
|    |    +--- org.slf4j:slf4j-api:1.7.25
|    |    +--- org.slf4j:slf4j-log4j12:1.7.25 (*)
|    |    +--- org.apache.logging.log4j:log4j-api:2.11.0
|    |    \--- org.apache.logging.log4j:log4j-core:2.11.0 (*)
|    +--- org.projectlombok:lombok:1.16.20
|    +--- org.slf4j:slf4j-api:1.7.25
|    +--- org.slf4j:slf4j-log4j12:1.7.25 (*)
|    +--- org.apache.logging.log4j:log4j-api:2.11.0
|    \--- org.apache.logging.log4j:log4j-core:2.11.0 (*)

**Comment by tatjana19** [comment]
Just add

```
packagingOptions {
    exclude 'log4j.properties'
}
```
in your app build.xml then Clean/sync project. I hope this helps.

**Comment by codeskraps** [comment]
@tatjana19 
Like I explained on the issue. That solution doesn't work, it solved the log4.properties but then there's another similar issue. Once you solve that one, something else comes up, until there's something I can fix.

@astrapi69 
After spending sometime, I was able to create a project importing a bunch a libraries I use on my main project until I was able to replicate the issue. I didn't go 1 by 1 so I still don't know which library is clashing with yours.

https://github.com/codeskraps/jgeohash_test

With library 2.4.0 I'm able to launch but with library 2.5 it fails with the error above.
https://github.com/codeskraps/jgeohash_test/blob/master/app/build.gradle#L71

**Comment by astrapi69** [comment]
Hey @codeskraps im not expert in gradle but i cloned the test repository and created a PR that contains a fix for your problem:

You have to add in the build.gradle file from your app in the defaultConfig:
```
android {
...
defaultConfig {
...
multiDexEnabled true
...
}
...
packagingOptions {
        exclude 'log4j.properties'
    }
}
dependencies {
...
    implementation ('de.alpharogroup:jgeohash-core:2.5') {
        exclude group: 'org.apache.logging.log4j', module: 'log4j-api'
        exclude group: 'org.apache.logging.log4j', module: 'log4j-core'
        exclude group: 'de.alpharogroup', module: 'silly-collections'
    }
...
}

```

I will create a patch version when i have time and deploy it. Help is welcome any time.

Cheers
@astrapi69

**Comment by tatjana19** [comment]
@codeskraps  did you tried out if the solution of @astrapi69 works? If yes i can close this issue.

**Comment by codeskraps** [comment]
I can confirm that the fix above by @astrapi69 works.

**Comment by astrapi69** [comment]
Hey @codeskraps, i have deployed a new patch version de.alpharogroup:jgeohash-core:2.5.2 that finally fixes this issue. I created also a second PR with the final fix in the [test project](https://github.com/codeskraps/jgeohash_test)
