### ISSUE TITLE
Enhancement: Implement ScalarFunction to include in Phoenix/HBase for spatial functions

### ISSUE THREAD

**Issue by threedliteguy** [astrapi69/jgeohash#4]
Add an example implementation that would allow using jgeohash for spatial indexes in Phoenix/Hbase.  
https://phoenix.apache.org/udf.html#How_to_write_custom_UDF

**Comment by threedliteguy** [comment]
Here's the way I got it to work without modifying Phoenix itself:
https://github.com/threedliteguy/General/wiki/Adding-spatial-data-queries-to-Phoenix-on-HBase

**Comment by astrapi69** [comment]
Hi @threedliteguy,

i didnt had time to have a look to it. If you have already implemented an example please send a pull request. I will look at the example and see what i can do.

**Comment by threedliteguy** [comment]
ok

**Comment by astrapi69** [comment]
Hi @threedliteguy,

this looks great. Shell i make a link to it or can i merge to the wiki of this project?

**Comment by threedliteguy** [comment]
You can merge it to your wiki if you want
I also created a ticket over there at Phoenix:
https://issues.apache.org/jira/browse/PHOENIX-2152?jql=project%20%3D%20PHOENIX%20AND%20text%20~%20spatial

**Comment by astrapi69** [comment]
I merged the example to the wiki. Here is a link to it:

https://github.com/astrapi69/jgeohash/wiki/Adding-spatial-data-queries-to-Phoenix-on-HBase

Thanks again for this example :-)
