### ISSUE TITLE
Get a sorted list by distance of a collection of geo location

### ISSUE THREAD

**Issue by tatjana19** [astrapi69/jgeohash#5]
See stackoverflow question:

http://stackoverflow.com/questions/12686626/is-there-a-geo-hashing-collection

**Comment by astrapi69** [comment]
Hi @tatjana19,

i wrote a few new methods that provide this functionality in the class LocationUtils.sortByDistance*. Look at the unit test(LocationUtilsTest) for a few examples with geohash values.
