### ISSUE TITLE
range queries or adjacent areas with bitwise accuracy

### ISSUE THREAD

**Issue by EclecticEngineer** [astrapi69/jgeohash#7]
I want to do a range query with bitwise accuracy rather than 5 bit accuracy (by truncating the string to however many characters I like).

The get adjacent areas is fantastic. It deals with the prime meridian and equator issues that would come up if I just did a range query by truncating to a specific number of bits.

A simpler option would be to add methods that would convert the geohash to and from a long value. Then I could truncate to an arbitrary number of bits then pass that value to a getAllAdjacentAreasList method which had an additional parameter indicating how many bits the geohash was using.

A more complex option would be to have a method like this:
    public static String[] getRange(String geohash, int numUnits, UnitType units)
Normally that method would return 2 values that identify a range. If the range crossed over the equator and/or prime meridian then it would return as many ranges as necessary to cover the area.

If it helps, my specific use case is as follows:
- I want to query a Cassandra DB for all objects within X meters of a point.
- The partition key would be the geohash truncated to 6 characters. That means a single partition could include an area up to 0.22 miles by 1.1 miles. All points would be duplicated into all 9 adjacent partitions so only a single query is required to retrieve all points within that area (just in case the point in question is right on the edge of the area).
- However, I do not want to actually transfer every point in that area back from Cassandra to the querying server. I want to do a range query that uses the clustering key to exclude as many points as possible. Ideally this means that I'd have 2 geohash values that would bound the range I'm looking for. If it crosses the prime meridian or equator then I guess 2 queries would be necessary.

I suppose that instead of this I could simply create a different table for every different resolution that I want to query for, but that would still require bitwise accuracy. In that case I'd still need the ability to get adjacent areas given a specific number of bits.

If I'm off the mark and there's a simple alternative then I'd love to hear about it.

**Comment by astrapi69** [comment]
Hi @EclecticEngineer can you give an example of it?

**Comment by EclecticEngineer** [comment]
Are you asking for an example implementation? I'll have to delve further into your code. I didn't actually look to see how getAllAdjacentAreasList worked, so I don't know whether it already works at bit level or if it only works at a string level. I'll have to look at it first.

The converting back and forth between the geohash and a long should be straightforward. I already looked at the code for that. The base32 alphabet for geohashes isn't one used by anyone else. It appears to prefer characters that are easy to tell apart (omitting characters like i and l). So a method would need to be provided that does base32 encoding or decoding using the custom alphabet.

    public long geohashToLong(String geohash) {
        // base 32 decode here
    }

    public String longToGeohash(long geohashLong) {
        // base 32 encode here
    }

If the caller then took the long value and truncated it to a specific number of bits, and then passed it to getAllAdjacentAreasList, would that work?

**Comment by marie-christin** [comment]
This would work if you Transfer the Long back to a String value, if the above methods are implement. @astrapi69 what do you think?

**Comment by astrapi69** [comment]
Yes if you transform back and the above methods are implemented.

**Comment by astrapi69** [comment]
@EclecticEngineer, i will close this issue. If you have a change request you can send me a pull request.
