### ISSUE TITLE
GeoHashUtils can not find class

### ISSUE THREAD

**Issue by LuoYuWuSheng** [astrapi69/jgeohash#8]
I‘m usring your jgeohash，and the version is 2.3.0
first，thanks to you
and i write my program like your example

GeoHashUtils.encode(53.5526394, 10.0067103);

but it just cann't resolve class GeoHashUtils
i doubt whether the version problem

**Comment by astrapi69** [comment]
Hello @LuoYuWuSheng,

i made with version 2.x.x some refactoring and i renamed the GeoHashUtils to GeoHashExtensions. So for the new version 2.x.x you would write 

GeoHashExtensions.encode(53.5526394, 10.0067103);

Thank you for your response i will change the docs appropriately.
